server {
        listen 80;
        server_name sarvinstylecoding.com www.sarvinstylecoding.com;
        location / {
                proxy_pass http://localhost:3000;
        }
        location /api/ {
                proxy_pass http://localhost:3001/;
        }
        location /mongo/ {
                proxy_pass http://localhost:8081;
        }

}