server_tokens off;
add_header X-Content-Type-Options "nosniff" always;
add_header X-Frame-Options "SAMEORIGIN" always;
add_header Referrer-Policy "strict-origin-when-cross-origin" always;
add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;

limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;


server {
        listen 80;
        server_name sarvinstylecoding.com www.sarvinstylecoding.com;
        return 301 https://$host$request_uri; 

}
server {
        listen 443 ssl;
        server_name sarvinstylecoding.com www.sarvinstylecoding.com;
        
        ssl_certificate /etc/letsencrypt/live/sarvinstylecoding.com/fullchain.pem; 
        ssl_certificate_key /etc/letsencrypt/live/sarvinstylecoding.com/privkey.pem;


        location / {
                proxy_pass http://web:3000;
        }    
        location /api/ {
                limit_req zone=api_limit;
                proxy_pass http://api:3001/;
        }          
        location /mongo/ {
                proxy_pass http://mongoExpress:8081;
        }

}

